# Generated by Django 5.1.5 on 2025-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_user_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
