# Generated by Django 5.1.5 on 2025-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
